host = "livecmt-2.bilibili.com"
port = 2243

# 用户id
user_id = 86896051

# 房间号
room_id = 21947054

# 不打印弹幕到控制台
no_print = false

# 每两次写入人气值的时间间隔，单位为分钟
log_interval = 3

# 人气阈值，低于阈值的人气记录不写人，此项用于过滤不直播时的人气值
log_threshold = 10

# 忽略特定用户的弹幕，在此列表中的UID发送的弹幕不会打印到控制台和写入到日志文件，一般用于屏蔽机器人弹幕
ignores = [383121293, 987654321]

# 银瓜子礼物不写入日志文件
no_silver = true